#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Allow Nginx HTTP through UFW
sudo ufw allow 'Nginx HTTP'

# Create necessary directories and files
sudo mkdir -p /var/www/html
sudo mkdir -p /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx server block
server_config=$(cat <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }

    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://youtube.com permanent;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF
)

# Write the server block configuration to the default Nginx site
echo "$server_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Enable the default Nginx site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo systemctl restart nginx
